blog_theme: light # Or use dark
name: Chalk
paginate: 25
url: https://dxmuses.github.io/github-pages-with-jekyll (format: https://example.com)
title: dx muses 
author: dxmuses
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Hey there! Welcome to my blog! This site is currently in the making.
    Please visit soon again to see some changes!
# social links
github_username:  dxmuses # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
